import { readFile, mkdir, writeFile, cp, rm } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
const root = fileURLToPath(new URL('../', import.meta.url));
const read = (p) => readFile(root + p, 'utf8');
const apps = JSON.parse(await read('src/data/apps.json'));
const site = JSON.parse(await read('src/data/site.json'));
const esc = (v) => String(v).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const slugs = new Set();
for (const app of apps) {
  if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(app.slug) || slugs.has(app.slug)) throw new Error('Invalid or duplicate app slug');
  slugs.add(app.slug);
  for (const key of ['name','category','status','tagline','description','platforms']) if (typeof app[key] !== 'string' || !app[key]) throw new Error(`Missing ${key}`);
  if (!Array.isArray(app.features) || app.features.some(f => !f.title || !f.body)) throw new Error('Invalid features');
}
if (site.contactEmail && !/^[^\s@<>]+@[^\s@<>]+\.[^\s@<>]+$/.test(site.contactEmail)) throw new Error('Invalid contact email');
if (site.contactUrl && new URL(site.contactUrl).protocol !== 'https:') throw new Error('Contact URL must use HTTPS');
const nav = [['/apps/','Apps'],['/about/','About'],['/contact/','Contact']];
const arrow = '<span aria-hidden="true">↗</span>';
function layout(title, path, content, description = '暮らしになじむ、小さな発見。Najimilabは、日常に小さな楽しみを添えるスマートフォンアプリをつくっています。') {
  return `<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} | Najimilab</title><meta name="description" content="${esc(description)}"><meta name="theme-color" content="#f8f8f0"><meta property="og:title" content="${esc(title)} | Najimilab"><meta property="og:description" content="${esc(description)}"><meta property="og:type" content="website"><meta property="og:locale" content="ja_JP"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/styles.css"></head><body><a class="skip" href="#main">本文へスキップ</a><header class="header wrap"><a class="brand" href="/" aria-label="Najimilab ホーム"><img src="/favicon.svg" width="32" height="32" alt="">Najimilab<span class="brand-dot">.</span></a><nav aria-label="メインナビゲーション">${nav.map(([url,label]) => `<a href="${url}" ${path.startsWith(url) ? 'aria-current="page"' : ''}>${label}${label === 'Contact' ? arrow : ''}</a>`).join('')}</nav></header><main id="main">${content}</main><footer class="wrap footer"><div><a class="brand" href="/">Najimilab<span class="brand-dot">.</span></a><p>日常に、なじむ。毎日が、ちょっと変わる。</p><small>© ${new Date().getUTCFullYear()} Najimilab</small></div><nav aria-label="フッターナビゲーション"><a href="/apps/">Apps</a><a href="/about/">About</a><a href="/privacy/">Privacy Policy <small>（下書き）</small></a><a href="/terms/">Terms of Service <small>（下書き）</small></a><a href="/contact/">Contact</a></nav></footer></body></html>`;
}
const heading = (en, title, desc) => `<div class="page-heading"><p class="eyebrow">${en}</p><h1>${title}</h1><p class="lead">${desc}</p></div>`;
const cards = () => apps.map((a,i) => `<article class="app-card"><div class="app-art"><span class="art-index">NAJIMILAB / APP ${String(i+1).padStart(2,'0')}</span><img src="/garden.svg" alt="" width="620" height="590" loading="lazy"><span class="art-caption">日々の一歩を、楽しみに。</span></div><div class="app-copy"><span class="badge"><span></span>${esc(a.status)}</span><p class="eyebrow">${esc(a.category)}</p><h3>${esc(a.name)}</h3><p>${esc(a.description)}</p><a class="text-link" href="/apps/${a.slug}/">アプリについて ${arrow}</a></div></article>`).join('');
const pages = new Map();
pages.set('index.html', layout('暮らしになじむ、小さな発見。', '/', `<section class="hero wrap"><div class="hero-copy"><p class="eyebrow"><span class="tiny-line"></span> SMALL IDEAS, EVERYDAY JOY</p><h1>暮らしになじむ、<br>小さな<span class="accent">発見。</span></h1><p class="hero-description">いつもの毎日に、ちょっとした楽しみを。<br>Najimilabは、あなたの日常にそっとなじむ<br class="desktop-break">アプリをつくる、小さな開発ラボです。</p><a class="button" href="/apps/">アプリを見てみる <span aria-hidden="true">↗</span></a></div><div class="hero-art"><span class="orbit-label">MADE FOR YOUR EVERYDAY</span><img src="/garden.svg" width="620" height="590" alt="スマートフォンと散歩道、緑の植物を描いたイラスト"><span class="art-note">a little spark in your everyday.</span></div></section><div class="wrap intro-strip"><span>日常に、なじむ。</span><p>便利さの、その先へ。<br>思わずまた使いたくなる体験を、一つずつ。</p><span class="strip-flower" aria-hidden="true">✳</span></div><section class="wrap section" id="apps"><div class="section-heading"><div><p class="eyebrow">OUR APPS</p><h2>毎日を、少し楽しく。</h2></div><a class="text-link" href="/apps/">すべてのアプリ ${arrow}</a></div>${cards()}<p class="quiet-note">ひとつずつ、ていねいに。これからのアプリも、ここからお届けします。</p></section><section class="about-band"><div class="wrap about-inner"><p class="eyebrow">ABOUT NAJIMILAB</p><div><h2>「なじむ」から、<br>新しい日常がはじまる。</h2><p>特別な日だけではなく、いつもの毎日に。<br>小さなアイデアと使いやすさを大切に、<br>暮らしに寄り添うアプリを育てていきます。</p><a class="text-link" href="/about/">Najimilabについて ${arrow}</a></div><span class="about-flower" aria-hidden="true">✳</span></div></section><section class="wrap contact-strip"><div><p class="eyebrow">GET IN TOUCH</p><h2>Najimilabへのお問い合わせ</h2></div><a class="button secondary" href="/contact/">Contact ${arrow}</a></section>`));
pages.set('apps/index.html', layout('Apps', '/apps/', `<section class="wrap section">${heading('OUR APPS','日常に寄り添うアプリ。','Najimilabが開発するアプリをご紹介します。')}${cards()}<p class="quiet-note">新しいアプリの情報は、このページで順次お知らせします。</p></section>`));
for (const a of apps) pages.set(`apps/${a.slug}/index.html`, layout(a.name, `/apps/${a.slug}/`, `<section class="wrap section"><a class="back-link" href="/apps/">← アプリ一覧へ</a><div class="detail-hero"><div><p class="eyebrow">${esc(a.category)}</p><span class="badge"><span></span>${esc(a.status)}</span><h1>${esc(a.name)}</h1><h2>${esc(a.tagline).replaceAll('\n','<br>')}</h2><p class="lead">${esc(a.description)}</p><p>${esc(a.platforms)}</p></div><img src="/garden.svg" width="620" height="590" alt="歩く楽しみをイメージしたイラスト。実際のアプリ画面ではありません。"></div><div class="feature-grid">${a.features.map((f,i) => `<article><span class="feature-number">0${i+1}</span><h3>${esc(f.title)}</h3><p>${esc(f.body)}</p></article>`).join('')}</div><div class="notice"><strong>ただいま開発中です</strong><p>掲載している内容は開発中の構想です。機能・デザイン・提供条件は変更になる場合があります。イラストはイメージであり、実際のアプリ画面ではありません。</p></div><div class="legal-links"><a href="/privacy/">Privacy Policy（下書き） ↗</a><a href="/terms/">Terms of Service（下書き） ↗</a></div></section>`, a.description));
pages.set('about/index.html', layout('About', '/about/', `<section class="wrap section">${heading('ABOUT NAJIMILAB','日常に、なじむ。','小さなアイデアから、毎日をちょっと楽しく。')}<div class="about-story"><span class="story-symbol" aria-hidden="true">✳</span><div><h2>暮らしのそばにある、<br>小さな開発ラボ。</h2><p>Najimilabは、日常に寄り添うスマートフォンアプリをつくる開発ブランドです。</p><p>何気ない移動や、いつもの習慣。その中にある小さな可能性を見つけ、使いやすく、続けたくなる体験にして届けることを目指しています。</p><p>最初のアプリ「懸賞ランナー」を開発しながら、これからも少しずつ、暮らしになじむアイデアをかたちにしていきます。</p></div></div><div class="feature-grid"><article><span class="feature-number">01 / SIMPLE</span><h3>迷わず、使える。</h3><p>毎日使うものだから、わかりやすさを大切に。</p></article><article><span class="feature-number">02 / DELIGHTFUL</span><h3>小さな楽しみを。</h3><p>日常の中に、思わずうれしくなるきっかけを。</p></article><article><span class="feature-number">03 / THOUGHTFUL</span><h3>一つずつ、ていねいに。</h3><p>使う人の目線で考え、少しずつ育てていきます。</p></article></div></section>`));
const contact = site.contactEmail || site.contactUrl;
pages.set('contact/index.html', layout('Contact', '/contact/', `<section class="wrap section narrow">${heading('GET IN TOUCH','お問い合わせ','Najimilabや開発アプリに関するお問い合わせについて。')}<div class="contact-box"><span class="contact-icon" aria-hidden="true">↗</span><h2>${contact ? 'お問い合わせ窓口' : 'お問い合わせ窓口を準備しています。'}</h2><p>${contact ? 'アプリ名とお問い合わせ内容を添えてご連絡ください。パスワードや認証コードなどの秘密情報は送らないでください。' : '正式な連絡先は、アプリのリリース前にこのページでお知らせします。現在、このサイトからお問い合わせを送信することはできません。'}</p>${site.contactEmail ? `<a class="text-link" href="mailto:${esc(site.contactEmail)}">${esc(site.contactEmail)} ↗</a>` : ''}${site.contactUrl ? `<a class="button" href="${esc(site.contactUrl)}">お問い合わせページへ ↗</a>` : ''}${!contact ? '<p class="todo">TODO：公開用メールアドレスまたはお問い合わせURLを設定する。</p>' : ''}</div><p class="quiet-note">個人情報の取り扱いについては<a href="/privacy/">Privacy Policy（下書き）</a>をご確認ください。</p></section>`));
for (const [slug,en,ja] of [['privacy','PRIVACY POLICY','プライバシーポリシー'],['terms','TERMS OF SERVICE','利用規約']]) pages.set(`${slug}/index.html`,layout(ja,`/${slug}/`,`<section class="wrap section legal">${heading(en,ja,'懸賞ランナーのリリースに向けた草案')}<article class="prose">${await read(`src/${slug}.html`)}</article></section>`));
pages.set('404.html',layout('ページが見つかりません','/404',`<section class="wrap section narrow">${heading('404 / NOT FOUND','ページが見つかりません。','URLが変更されたか、ページが存在しない可能性があります。')}<a class="button" href="/">トップページへ戻る ↗</a></section>`));
await rm(root + 'dist', {recursive:true, force:true});
await mkdir(root + 'dist', {recursive:true});
await cp(root + 'public', root + 'dist', {recursive:true});
for (const [path, html] of pages) { await mkdir(root + 'dist/' + path.split('/').slice(0,-1).join('/'),{recursive:true}); await writeFile(root + 'dist/' + path, html); }
console.log(`Built ${pages.size} static pages. No client JavaScript or external assets.`);
